ciudad= input("ciudad deseada:")
import turtle
turtle.color("blue")
turtle.pensize(3)
turtle.circle(30)
turtle.penup()
turtle.setpos(70,-0)
turtle.pendown()
turtle.color("black")
turtle.pensize(3)
turtle.circle(30)
turtle.penup()
turtle.setpos(140,-0)
turtle.pendown()
turtle.color("red")
turtle.pensize(3)
turtle.circle(30)
turtle.penup()
turtle.setpos(35,-30)
turtle.pendown()
turtle.color("yellow")
turtle.pensize(3)
turtle.circle(30)
turtle.penup()
turtle.setpos(105,-30)
turtle.pendown()
turtle.color("green")
turtle.pensize(3)
turtle.circle(30)
turtle.penup()
turtle.setpos(0,-60)
turtle.pendown()
turtle.color("black")
turtle.write((ciudad.upper()) + ' 2020', font=("Times New Roman", 20,))
